### ISSUE TITLE
Shake Gesture does not work on Motorola X Play (already used by native OS)

### ISSUE THREAD

**Issue by brunoreis** [expo/expo-docs#126]
Hi, please, how can I see the developer menu on Motorola X Play? The normal behaviour is to show the camera.

**Comment by brentvatne** [comment]
Hi there! You will need to disable that behavior currently: https://github.com/facebook/react-native/issues/13490

We may come up with an alternative though, any suggestions? Tracking this on: https://github.com/expo/expo/issues/517

**Comment by brunoreis** [comment]
When I slide down from the top I see that menu with the notifications and there is also the name of the app in a blue bar with buttons to pin, share and reload. I think there would be a safe place to not conflict. But, I imagine that could run into to risk of unwanted people going to developer menu. But, well, shake gesture also run into that risk. Let's see... what about holding for a while there to open the menu and enable a little movable overlay button over the app screen.

**Comment by brunoreis** [comment]
Turning of the camera gesture unfortunately does not enable using the developer menu.
