### ISSUE TITLE
MapView: Steps for Standalone Android not working/incomplete

### ISSUE THREAD

**Issue by yannickschuchmann** [expo/expo-docs#140]
Hey,
I haven't found any template for submitting issues so I just try to do my best to be understandable.

## Problem:
Currently there are additional steps from the documentation required to make MapView work with a standalone Android app. But after following these steps in detail you end up having a screen with a blank map and a Google logo in the lower left corner. This is only true for standalone Android installed via Play Store. On iOS and Android installed via `adb install` it's fine.

## Solution:
User atinder90 was so kind to post his solution in the [forum](https://forums.expo.io/t/mapview-not-working-in-app-released-to-play-store/2155/9). In summary it is important that one generates the SHA-1 fingerprint for API key restrictions based on the **derived apk** from play store instead of the previous built apk.

## Proposal:
Would be great to have the part of fingerprint generation in the MapView docs updated with the mentioned solution.

**Comment by abi** [comment]
Great catch, can you send us a PR? :) https://github.com/expo/expo-docs/blob/master/versions/unversioned/sdk/map-view.md

**Comment by brentvatne** [comment]
sorry I don't understand the problem. I have followed the exact steps and it worked as expected :\

**Comment by jimmylee** [comment]
I'm going to close this issue since its been a while since any follow up. Feel free to open another issue if more problems arise.
