### ISSUE TITLE
Errors using generator functions

### ISSUE THREAD

**Issue by aaronlangford31** [expo/expo-docs#141]
Please forgive me for my illiteracy in React-Native, Babel, etc. Will try to explain this with most detail possible.

After scaffolding the app with Expo's tools, I followed a few tutorials to wrap the app in Redux. I'm using Sagas as my middleware for handling server requests, and other heavy duty operations.

Sagas make use of generator functions to work their magic. After I added in the saga middleware, I began seeing an error: `TypeError: Cannot read property 'mark' of undefined`. This error goes away when I don't import my sagas into the file where I'm setting up my middleware. Further investigation reveals that the specific place in the transpiled JS wher this TypeError is happening is here:

```
var _reduxSaga = require(737         ); // 737 = redux-saga

var _effects = require(751                 ); // 751 = redux-saga/effects

var _expo = require(12    ); // 12 = expo

var _vectorIcons = require(564                 ); // 564 = @expo/vector-icons

var _types = require(757               ); // 757 = ../actions/types

var _app = require(761             ); // 761 = ../actions/app

var _marked = regeneratorRuntime.mark(loadAssetsAsync),  <----------- HERE
    _marked2 = regeneratorRuntime.mark(watchLoadAppAssets);

var regeneratorRuntime = require(191                  ); // 191 = regenerator-runtime
```

To me, this appears to be an issue with Babel. The regeneratorRuntime is undefined when marking my generator functions.

Something tells me this could be an upstream issue, but I'm unsure where to go upstream. Furthermore, a buddy of mine has his RN app working just fine with redux sagas, but he is not using Expo.

Would love thoughts and help on this issue!

**Comment by jsvg** [comment]
I'm seeing a similar issue.

Defining any generator function seems to throw an error, e.g. `function* test() {}` will throw `undefined is not an object (evaluating 'regeneratorRuntime.mark')`

Potentially linked to this: https://github.com/facebook/react-native/issues/14838

**Comment by abi** [comment]
Also, should be a bug on `expo/expo` rather than here @dikaiosune

**Comment by dikaiosune** [comment]
Oops, sorry, didn't notice the repo. Yes, please move this over there, or to our forums.
