### ISSUE TITLE
Location reverseGeocodeAsync returns incorrectly

### ISSUE THREAD

**Issue by sim-stamplet** [expo/expo-docs#143]
reverseGeocodeAsync doesn't return the correct location in text and always return only one result for all coordinates tested 
Array [
  Object {
    "name": "North Atlantic Ocean",
  },
]
expected Result is more detailed with street, city and other details : 
https://github.com/expo/expo-docs/blob/master/versions/v19.0.0/sdk/location.md

**Comment by abi** [comment]
This sounds more like a bug on `expo/expo` than in docs. cc @dikaiosune

**Comment by brentvatne** [comment]
please create an example on snack.expo.io, and post it along with a description of what you expect to see and what you actually see on http://github.com/expo/expo
