### ISSUE TITLE
To run it on your iOS device -> missing in docs >= sdk 20.0.0

### ISSUE THREAD

**Issue by aniltirola** [expo/expo-docs#162]
today we built a standalone app for android with 'exp build:android' --> everyting ok;
then we built a standalone app with for ios with 'exp build:ios' --> build ok --> but then we had problems to install on device;

so in the document for sdk <= 19.0.0, there was the paragraph "To run it on your iOS device, ....";

this paragraph is missing for sdk >= 20.0.0;

1. Is this paragraph from "sdk <= 19.0.0" still valid?

2. if still valid, is there a little bit more information for doing testflight and enable ios device for testing?

thanks
anil

**Comment by abi** [comment]
I believe the only way to test a production build on the device is to use TestFlight. (Download the .ipa file that's generated, set up TestFlight on Apple's website, upload IPA) Someone added a section about using TestFlight recently to the docs (yet to be deployed).
