### ISSUE TITLE
Cannot Install or run exp cli

### ISSUE THREAD

**Issue by Quadriphobs1** [expo/expo-docs#175]
Each time i run `npm i -g exp` i get same error as this
npm WARN react-redux@5.0.6 requires a peer of react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0 but none is installed. You must install peer dependencies yourself.

npm ERR! code EINTEGRITY
npm ERR! sha512-ybLKof9FyVAhNY+hVyGVQF2Br65uyYfrkBNTdiyxfObiHdSn8zvrZ/B62a3E0bbnb6f9VSpcVSfvEJtPqG0wMg== integrity checksum failed when using sha512: wanted sha512-ybLKof9FyVAhNY+hVyGVQF2Br65uyYfrkBNTdiyxfObiHdSn8zvrZ/B62a3E0bbnb6f9VSpcVSfvEJtPqG0wMg== but got sha512-AT7bYoV46OmsUJlhq4nN/xQcXhN94EyxfUFF8NxuPAVZk9Z6HtHxKmge18MnI8Uyy4W9E1gagYE6NoaLitf5rg==. (18185846 bytes)

and i can't run any exp commands and i need to detach the exp project how can i go about this

**Comment by abi** [comment]
That's weird, but please open the issue on expo/expo, rather than here. You'll probably get a quicker answer on our Slack.

**Comment by Quadriphobs1** [comment]
No bo seems to answer me on slack i posted the question therr

**Comment by Edward-Alozieuwa** [comment]
hi, please i am having the same issue and i cant find a solution
