### ISSUE TITLE
Scroll position doesn't always work properly

### ISSUE THREAD

**Issue by wodin** [expo/expo-docs#179]
While fixing some typos in the Glossary I found that the scroll position doesn't always work well.

e.g. if you scroll down to the exp entry in the Glossary and click on the Read more link you get taken to guides/exp-cli.html, but instead of being positioned at the top of the page the scroll position is a little way down the page, as if something is remembering the scroll position in the Glossary and restoring it.

Another example: Go to https://docs.expo.io/versions/latest/guides/linking.html and scroll to the bottom. Then click on the `WebBrowser` link in the `Example: using linking for authentication` section. This will take you to https://docs.expo.io/versions/latest/sdk/webbrowser.html, but the scroll position will not be at the top of the page. Also, (in Firefox, but not Chromium/Chrome) if you scroll to the top of webbrowser.html and then click the Back button in the browser, you get taken to the top of linking.html instead of to where you originally came from.

Also, clicking on an anchor (e.g. #yarn in the Package Manager entry) takes you to the right place, but clicking the browser's Back button does not take you back to where you were before clicking on the anchor.

This is with Firefox 56.0/Chromium 61.0.3163.100 on Linux and Firefox 56.0/Chrome 61.0.3163.100 on Mac.

**Comment by brentvatne** [comment]
hi there! can you submit a pr for this if it is important to you? I haven't noticed it before.

worth noting also that we're currently re-writing our docs to use next.js, perhaps a fix will just fall out of that, cc @abi

**Comment by wodin** [comment]
Hi

Do you mean you can't reproduce this? Or that you just don't notice it unless you're specifically looking for it?

I suspect this behaviour could cause some slight confusion for people following internal links in the docs. Unfortunately I don't know where the problem is, so I don't have a pull request for you. Since you're moving to next.js it's probably not worth worrying about this until that's been done.

FYI, I tried reproducing it on gatsbyjs.org/docs but was not able to, except for the following, which I can reproduce on Firefox 57.0.1 and Chrome 62.0.3202.94 on Mac and Firefox 56.0/57.0.1 and Chromium 62.0.3202.94 on Linux:

On https://www.gatsbyjs.org/docs/deploy-gatsby/, scrolled all the way to the top, click on one of the top three links, e.g. GitLab Pages. That should scroll down the page to the right section. Now click the browser's Back button and nothing happens, except the fragment is removed from the URL in the location bar. I'll report this issue there. Strangely I cannot reproduce this on Edge on Windows 10.

One difference I notice between the Gatsby and Expo docs is that Gatsby's pages all look like /docs/some-page/, whereas Expo's all look like .../section/page.html. Just a wild guess and no idea why that might cause a problem.

**Comment by abi** [comment]
@wodin Thanks for pointing this out! I can repro your second example on the linking page. Maintaining correct scroll position is definitely important for good UX. On our next.js website, this should be fixed.

**Comment by wodin** [comment]
FYI, this is mostly fixed now, but this part is still a problem:
> Also, clicking on an anchor (e.g. #yarn in the Package Manager entry) takes you to the right place, but clicking the browser's Back button does not take you back to where you were before clicking on the anchor.
