### ISSUE TITLE
Dash Integration

### ISSUE THREAD

**Issue by charliemitchell** [expo/expo-docs#181]
Hello,
Can someone really cool, smart and awesome create a version for Dash? I know there has to be someone involved in this project that could wave a magic wand, bark some incantations, and produce a Dash doc set for Expo in a short amount of time. If you're reading this, It's probably you. Imagine the praise and glory you'll receive for pulling this off! 🤣 

[Dash](https://kapeli.com/dash)

Maybe...
[dash-docset-generator](https://github.com/brynbellomy/dash-docset-generator)

**Comment by brentvatne** [comment]
@charliemitchell sounds cool, I don't use dash though, maybe you can do it ;)
