### ISSUE TITLE
how to Create an Android OAuth Client ID

### ISSUE THREAD

**Issue by omarshiha** [expo/expo-docs#189]
i am following the steps to create an Android OAuth Client ID to enable google sign in for my react native app, but dont know how to Create an Android OAuth Client ID as when i run this comman 'openssl rand -base64 32 | openssl sha1 -c' it gives me this ERROR  "openssl' is not recognized as an internal or external command"!

**Comment by brentvatne** [comment]
ah, sounds like you might need to install openssl. Instructions may vary depending on whether you're running windows/macos/linux/whatever -- on mac I would run `brew install openssl`, try googling the alternative for your platform

**Comment by omarshiha** [comment]
i installed it but still error, i type it exactly like this
rand -base64 32 | openssl sha1 -c
is there anything wrong ?

**Comment by brentvatne** [comment]
i've never had this problem before. can you try googling this problem? the instructions i gave there apply to any android project so there are probably many more resources out there

**Comment by jimmylee** [comment]
Closing this issue, feel free to reopen if the problem occurs again.
