### ISSUE TITLE
docs.expo.io connection is not secure

### ISSUE THREAD

**Issue by jean** [expo/expo-docs#190]
Firefox warns that the site is not secure because of mixed content. 
This is not a good look. 

![screenshot from 2017-11-08 16-04-50](https://user-images.githubusercontent.com/84800/32540228-9dbb148c-c49e-11e7-8725-2e73c2afd544.png)

**Comment by brentvatne** [comment]
Chrome doesn't have an issue with it -- @skevy, any idea what's going on here?

**Comment by skevy** [comment]
It's not clear to me why this is happening to you...every browser I use shows the page as encrypted. Can you try a different browser to see if you get a different result?

**Comment by jean** [comment]
Hmm! Now Firefox is :100: too ... I'll reopen with more details if I see it again ..
