### ISSUE TITLE
Document how to set custom "Permissions" messages

### ISSUE THREAD

**Issue by alexrussell** [expo/expo-docs#198]
It'd be really useful (until [my feature request](https://expo.canny.io/feature-requests/p/customisable-permission-descriptions) is implemented 😉 ) if the docs could mention how one could set custom descriptions associated to Permissions usages.

This actually came from me having an app rejected from the App Store due to (in part) accessing the camera without giving a reason other than the default "My App needs to access the camera" kinda thing. I found out that I could, for iOS at least, use the [`ios.infoPlist`](https://docs.expo.io/versions/latest/guides/configuration.html#infoplist) key in `app.json` to set these custom things myself. I think it may be worth making mention of this on the [Permissions](https://docs.expo.io/versions/latest/sdk/permissions.html) docs page, and also how this can be done in Android if that is something that *can* be done at this point.

**Comment by brentvatne** [comment]
it sounds like you know how to do this, can you submit a PR to add it?

**Comment by alexrussell** [comment]
I'm more than happy to do so but I can only talk for iOS. I have no idea how to do the same thing in Android (or whether you can or even need to). That's why I opened this as an issue rather than a PR - I don't have the full knowledge.

Shall I go ahead and do so for iOS only, or leave this open for someone with knowledge of both methods to do properly?

**Comment by fvieira** [comment]
I just had my app rejected on iOS for the same reason, and had no problem on Android, so I'd say having this for iOS only would already be useful!

**Comment by alexrussell** [comment]
@fvieira turns out this is done: https://docs.expo.io/versions/latest/guides/app-stores.html#system-permissions-dialogs-on-ios

Closing!
