### ISSUE TITLE
Possible Unhandled Promise Rejection :TypeError this.camera.takePicture() is not a function

### ISSUE THREAD

**Issue by NaveenDK** [expo/expo-docs#207]
I have the same code as shown in the repo : But not sure why I am getting the error saying the above , any help would be great! 
Thanks

**Comment by AdamJNavarro** [comment]
Hey NaveenDK,

If you haven't resolved this issue, can you please create a post on our forums https://forums.expo.io/ with all relevant code and information. This way if other Expo users run into the same issue, they can see how it was (hopefully) fixed.

Cheers,

Adam
