### ISSUE TITLE
detaching for ios native modules

### ISSUE THREAD

**Issue by sasssssha** [expo/expo-docs#213]
Greetings, I need some modules which use native code for my project and i decided to make a detach
But this part of docs isn't clear for me:

> 3. iOS: Configure, build and run
This step ensures the native iOS project is correctly configured and ready for development.  
-Make sure you have the latest Xcode.
-If you don’t have it already, install CocoaPods, which is a native dependency manager for iOS.
-Run pod install from your project’s ios directory.
-Open your project’s xcworkspace file in Xcode.
-Use Xcode to build, install and run the project on your test device or simulator. (this will happen by default if you click the big “Play” button in Xcode.)
**Once it’s running, the iOS app should automatically request your JS bundle from the project you’re serving from XDE or exp.**

So, I have a few issues
1.When i make detach i can't load bundle in my expo client on my phone(just nothing happens after scanning qr)
2.Am i still able to write only JS, without any native code? Because I need only a few native modules
3.Are this steps necessary if i don't need to write native code?

**Comment by AdamJNavarro** [comment]
Hey sassssha, I'll try and shed some light on your questions:

1. Once your project uses native modules that aren't part of the Expo SDK, you need to build the app via Xcode or Android Studio and run it with those programs. The Expo client isn't able to run additional native modules.

2. Once you detach your project, you can make any native code changes you want.

3. Detaching is only necessary if you are making additional native code changes. If the library you are trying to use instructs you to run react-native link or make manual changes to native code, you have to detach. 

Hopefully that helps you understand your situation better. For future reference though, please direct questions like these to the Expo Forums (https://forums.expo.io/) or the Expo Slack (https://slack.expo.io/)! We try to keep it where only bugs/errors are post on Github.

Cheers,

Adam

**Comment by sasssssha** [comment]
Thx for reply, AdamJNavarro
But I still don't understand if i am able write only jsx without native code (use only linked modules)
And why i get no result while trying to open app in client right after detach

**Comment by eriveltonelias** [comment]
Hey @sasssssha! 
Yes, you're able to keep working with just JS ( You don't need to write native code if you don't want and you can use native modules ), and since you detach you need run it on Xcode and/or Android Studio has @AdamJNavarro told you. 

So, when you detach, to emulate your app need have run your project ( exp start or by XDE ) and run it on Xcode or Android Studio, to see it on the device you need follow the instructions for install the app in your phone ( IOS by Xcode or Android by Android Studio )

**Comment by eriveltonelias** [comment]
@ide @brentvatne 

can you close this issue?
