### ISSUE TITLE
registerForPushNotificationsAsync clarification

### ISSUE THREAD

**Issue by Architektor** [expo/expo-docs#216]
Hello guys, can anybody explain what actually `registerForPushNotificationsAsync ` is?
The [example](https://docs.expo.io/versions/latest/guides/push-notifications.html#3-handle-receiving-andor-selecting-the-notification) from the docs just tells to import and call it,
but i don't have `registerForPushNotificationsAsync` module and i'm getting an error that it is not found in module map. Can someone clarify me a bit what it is and where to get it?

**Comment by truca** [comment]
I found an example [here](https://snack.expo.io/ry526Qu3e)

**Comment by eriveltonelias** [comment]
Hi @Architektor! 
`registerForPushNotificationsAsync ` isn't a module, it's just a function that gets your push token and sent it to your server ( if you have it ) every time when your app is loaded, and you can found it on `/api` folder.

**Comment by eriveltonelias** [comment]
@brentvatne can you close this issue?

**Comment by ide** [comment]
We'll update the docs for the next SDK to make this clearer.
