### ISSUE TITLE
can I install on real iPhone device from Mac virtual machine? 

### ISSUE THREAD

**Issue by nicoara** [expo/expo-docs#218]
Hello,

I have a virtual machine with MacOS on a Windows host. I want to be able to run the Expo app on my own real iPhone device. How to proceed, given that the exp://192.168,0.2 is a local address that is not visible outside the virtual machine?
Inside Expo XDE, the Device button shows only the simulator, and Share will provide a qr code with the local address.

Thank you

**Comment by nicoara** [comment]
hello, anyone is paying attention to the issues forum?

**Comment by eriveltonelias** [comment]
Hi @nicoara, 

You can just change your Host setting on your Expo XDE, try to change `LAN` to `Tunnel`, will work.

**Comment by jimmylee** [comment]
Thanks @eriveltonelias, since there hasn't been any dialogue for a while, I'm closing this issue. Feel free to open a new one if changing to `LAN` or `Tunnel` didn't work for you.
