### ISSUE TITLE
Update "Using GraphQL" with Apollo Client 2.0 example

### ISSUE THREAD

**Issue by ceefour** [expo/expo-docs#223]
Currently this is out-of-date and will not work:

https://github.com/expo/expo-docs/blob/master/versions/v24.0.0/guides/using-graphql.md

Reason: https://github.com/apollographql/apollo-client/issues/2458#issuecomment-341436641

New instructions: https://github.com/apollographql/apollo-client/blob/master/Upgrade.md

**Comment by jimmylee** [comment]
Closing this since we have had a couple of SDK revisions since then. I don't see any current references to createNetworkInterface
