### ISSUE TITLE
wrong size after resize with Image Manipulator

### ISSUE THREAD

**Issue by insaneadinesia** [expo/expo-docs#228]
Hello,
In the latest expo sdk version, I use Image Manipulator to resize local image before upload to server. But I found something wrong. 

I resize image to height: 100 and width: 100. In the promise after image resized, it say height and width is 100 (just like what I want), but after I upload image to server and download that image to my local computer, the dimensions is not 100 x 100, but 200 x 200.

Just wonder, maybe there's anybody who have the same problems..

Thank you,

**Comment by jimmylee** [comment]
Hey @insaneadinesia, the best place to post this on our:

https://forums.expo.io
https://slack.expo.io

Sorry it took so long for anyone to get to this. Feel free to open another issue if you find any issues with our docs.
