### ISSUE TITLE
Increase Documentation section size

### ISSUE THREAD

**Issue by suhshinhwang** [expo/expo-docs#230]
I'm reading the documentation and find it difficult to find where the separation of parameters/methods/props are. Take a look at below example (taken from the [AV documentation](https://docs.expo.io/versions/latest/sdk/av.html)). The words `Parameters` and `Returns` are much bigger and have heavier font weight than the method itself (`playbackObject.replayAsync(statusToSet)`).

This is incredibly awkward especially when I'm scrolling up/down fast. Take a look at a React Native props documentation (e.g. [Keyboard props](https://facebook.github.io/react-native/docs/keyboard.html#removelistener)), it's very clear where one prop ends and where the other prop starts.

![Documentation text](https://preview.ibb.co/eNM4wb/Screen_Shot_2018_01_03_at_3_27_46_PM.png)

**Comment by jimmylee** [comment]
We've updated the documentation visually since Jan 3rd so I'm closing this now.
