### ISSUE TITLE
Font.loadAsync() returning Promise is not documented

### ISSUE THREAD

**Issue by carsonwah** [expo/expo-docs#234]
### Related page:
https://docs.expo.io/versions/latest/sdk/font.html

### Now
The doc states that `Font.loadAsync()` "Doesn’t return anything".

### Expected
`Font.loadAsync()` is actually returning a Promise object just like that in [`Asset.loadAsync()`](https://docs.expo.io/versions/latest/sdk/asset.html#expoassetloadasyncmodules).

### Comment
It is misleading as I was following [Preloading & Caching Assets](https://docs.expo.io/versions/latest/guides/preloading-and-caching-assets.html) example. It has a function like this:

```
function cacheFonts(fonts) {
  return fonts.map(font => Font.loadAsync(font));
}
...
const fontAssets = cacheFonts([FontAwesome.font]);
await Promise.all([...imageAssets, ...fontAssets]);
```

This function is expected to take in an array of objects and return an array of Promises. So "`Font.loadAsync()` returns a Promise" should be cleared stated.

**Comment by brentvatne** [comment]
> Returns a promise. The promise will be resolved when the fonts have finished loading.
