### ISSUE TITLE
`Install and configure Sentry` section is not clean

### ISSUE THREAD

**Issue by nixololo** [expo/expo-docs#261]
[Sign up for a Sentry account and create a project](https://docs.expo.io/versions/latest/guides/using-sentry.html#sign-up-for-a-sentry-account-and-create-a-project) section on sentry integration docs described pretty well and have all information that you need to finish this step.
But [Install and configure Sentry](https://docs.expo.io/versions/latest/guides/using-sentry.html#open-appjson-and-add-a-postpublish-hook) not really clean as docs don't point that your `authToken` should have `project:write` scope enabled.

So it will be nice to have such note with a link to [sentry source map docs](https://docs.sentry.io/clients/javascript/sourcemaps/#uploading-source-maps-to-sentry).

**Comment by brentvatne** [comment]
can you submit a PR?

**Comment by nixololo** [comment]
@brentvatne yep can do in a couple of days 👍

**Comment by jimmylee** [comment]
Thank you @nixololo ! Closing this.
