### ISSUE TITLE
components life cycle methods

### ISSUE THREAD

**Issue by moskh** [expo/expo-docs#267]
I do not know if this is a serious issue, but most subscriptions in the documentation are used in the componentWillMount method, but according to the official React documentation on this method (
@https://reactjs.org/docs/react-component.html#componentdidmount):

> Avoid introducing any side-effects or subscriptions in this method. For those use cases, use componentDidMount() instead.

Could someone correct me if I am wrong?

**Comment by jimmylee** [comment]
What are you concerned about?

**Comment by moskh** [comment]
According to the react documentation, componentWillMount is deprecated.

**Comment by brentvatne** [comment]
yeah we should update this to add subscriptions in `componentDidMount`! pr welcome
