### ISSUE TITLE
Push Notification Table

### ISSUE THREAD

**Issue by nthgol** [expo/expo-docs#275]
on iOS, the Notifications.addListener picks up all three allowable cases in the table below:
![image](https://user-images.githubusercontent.com/26420958/38147671-473d5e42-3421-11e8-800e-f0216476e278.png)

Please update the table to make it clear that reaching into props.exp.notification in App.js (root component) is not necessary? (Maybe someone can confirm this on android.)
Additionally, i find that the origin on iOS is "selected" for either of the 2 cases where the app is closed/backgrounded, while it is 'received' when foregrounded. 

_I don't have mac so I cannot update this 'sketch'. I am happy to do this update if providing a png is all that's needed.._

**Comment by jimmylee** [comment]
@nthgol you bring up some really good points.

I think submitting a png is all thats needed, but I should just make it a markdown table instead because theres no point for it to be an image.

**Comment by jimmylee** [comment]
I've updated the docs to use a table. There are some issues with using `{`, `}`, and other symbols besides plain text for now, but I'll look into getting those resolved.

Feel free to submit a PR if you want any of that information changed.
