### ISSUE TITLE
Error while gathering & validating credentials

### ISSUE THREAD

**Issue by linfeizhang** [expo/expo-docs#282]
![Uploading QQ20180413-143726.png…]()

**Comment by linfeizhang** [comment]
provisioning profiles from your Apple Developer account.

Note: Expo does not keep your Apple ID or your Apple password.

? What's your Apple ID? 
? Password? [hidden]
14:22:30 [exp] Validating Credentials...
14:22:36 [exp] Only 1 team associated with your account, using Team ID: 
? Will you provide your own Distribution Certificate? Let Expo handle the proces
s
? Will you provide your own Push Certificate? Let Expo handle the process
14:23:11 [exp] Error while gathering & validating credentials
14:23:11 [exp] Reason:Unexpected response, raw:{"responseId":"3422ea6a-14f6-4f3b-bef6-9beb72e3d9c7","resultCode":1200,"resultString":"You are not allowed to perform this operation.  Please check with one of your Team Admins, or, if you need further assistance, please contact Apple Developer Program Support. https://developer.apple.com/support","userString":"You are not allowed to perform this operation.  Please check with one of your Team Admins, or, if you need further assistance, please contact Apple Developer Program Support. https://developer.apple.com/support","creationTimestamp":"2018-04-13T06:23:11Z","protocolVersion":"QH65B2","userLocale":"en_US","requestUrl":"https://developer.apple.com/services-account/QH65B2/account/ios/certificate/submitCertificateRequest.action","httpCode":200}
14:23:11 [exp] Set EXPO_DEBUG=true in your env to view the stack trace.

**Comment by jimmylee** [comment]
Hey @linfeizhang thanks for sharing some of the problems you are having.

To get support, you should post to:

https://slack.expo.io
https://forums.expo.io

I'm going to close this. Feel free to submit another issue if you have some ideas for how to improve our documentation, and feel free to submit a PR if we should update a certain part of our docs.
