### ISSUE TITLE
versionpatch.sh: can't find file to patch at input line

### ISSUE THREAD

**Issue by riwu** [expo/expo-docs#284]
When creating https://github.com/expo/expo-docs/pull/283, I tried to run `versionpatch.sh` but got the following error:
```
expo-docs$ ./scripts/versionpatch.sh unversioned v26.0.0
Patching in /Users/a/Desktop/Github/expo-docs
can't find file to patch at input line 5
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/versions/unversioned/sdk/filesystem.md b/versions/unversioned/sdk/filesystem.md
|index 442a4e7..a7ac7dd 100644
|--- a/versions/unversioned/sdk/filesystem.md
|+++ b/versions/unversioned/sdk/filesystem.md
--------------------------
File to patch: 
```

**Comment by jimmylee** [comment]
Are you still getting this error? Sorry I missed this issue I should have followed up sooner :(

**Comment by riwu** [comment]
Did you update the script?
https://github.com/expo/expo-docs/commit/92808fdbf0296af648f4c28df053da9fc15b7c5c you removed the `scripts` folder  but did not add the `__internal__` folder. Gitignored perhaps?

**Comment by jimmylee** [comment]
I'll restore the scripts folder since people depend on this.

**Comment by jimmylee** [comment]
I've restored the scripts folder, sorry about that @riwu that must've looked really weird on our part 😆

**Comment by riwu** [comment]
Np. Just tested it, still getting same error as above. It does work if I enter `sdk/filesystem.md` in the subsequent `File to patch:` prompt though.

**Comment by brentvatne** [comment]
works on my machine right now:

```
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   versions/unversioned/guides/offline-support.md

no changes added to commit (use "git add" and/or "git commit -a")
╭─~/universe/docs ./scripts/versionpatch.sh unversioned v27.0.0
Patching in /Users/brentvatne/universe/docs
patching file guides/offline-support.md
```
