### ISSUE TITLE
Offline support maybe have something wrong?

### ISSUE THREAD

**Issue by zhaozhiming** [expo/expo-docs#286]
Hi, I found the sentence in `offline-support.md` maybe have a little problem.  
The sentence as follow. Should it be `To **unable** background JS downloads...`? 
Because `fallbackToCacheTimeout` is the time to fetch updates before use cached. 
So when it set to 0, it will not download JS update and use cached immediately.  
Am I right? Or something I misunderstand?  Please Help. Thanks.

> ## Load JS updates in the background
>
> To **enable** background JS downloads, set updates.fallbackToCacheTimeout to 0 in app.json

The fallbackToCacheTimeout defined: 

> ### fallbackToCacheTimeout
> 
> How long (in ms) to allow for fetching OTA updates before falling back to a cached version of the app. Defaults to 30000 (30 sec). Must be between 0 and 300000 (5 minutes).

**Comment by brentvatne** [comment]
I agree this wording is not clear! Updated docs to improve it
