### ISSUE TITLE
Audio API reference examples several months out of date on expo.io

### ISSUE THREAD

**Issue by thekyriarchy** [expo/expo-docs#291]
https://docs.expo.io/versions/latest/sdk/audio.html

- https://github.com/expo/audio-recording-example/issues/8
- https://github.com/expo/playlist-example/issues/12

**Comment by jimmylee** [comment]
I've updated https://expo.io/@community/audio-recording-example so that it is using SDK21 which should work for now.

If you end up stumbling upon a really cool audio example/kitchensink or making your own, I'd love to replace it.
