### ISSUE TITLE
Lottie code sample not working

### ISSUE THREAD

**Issue by lee5214** [expo/expo-docs#297]
I copied this sample code from [here](https://docs.expo.io/versions/v27.0.0/sdk/lottie) into an empty screen of my project, it shows only the restart button, the animation didn't render.

error message:
```
[Unhandled promise rejection: SyntaxError: JSON Parse error: Unexpected identifier "undefined"]
```
So I checked the code and found out this function causing this problem.
```
_loadAnimationAsync = async () => {
    let result = await fetch(
      'https://cdn.rawgit.com/airbnb/lottie-react-native/635163550b9689529bfffb77e489e4174516f1c0/example/animations/Watermelon.json'
    );

    this.setState(
      { animation: JSON.parse(result._bodyText) },
      this._playAnimation
    );
  };
```
It uses fetch() to query JSON data, it returns a promise but didn't handle the response. 
react-native doc about fetch [read here](https://facebook.github.io/react-native/docs/network.html)
And we should avoid using '._bodyText' directly [read here](https://github.com/github/fetch/issues/274)

I think it may works before, but some version changes cause it breaks now. The easy fix is to refactor this method with promise. 

my environment:
```
node: v10.0.0
react-native-cli: 2.0.1
react-native: 0.54.0
expo: 27.0.0
```

**Comment by lee5214** [comment]
I refactored the method and saved into a snack sample [here](https://snack.expo.io/Byu2WM2af).
Tested, it works for each version, so I submitted a pr for quick fix, please check.
#298

**Comment by jimmylee** [comment]
Thank you so much @lee5214 and I'm so sorry it took me so long to get back to you. I've landed your PR and I love the animation.
