### ISSUE TITLE
Typo in Haptic Control Doc

### ISSUE THREAD

**Issue by johnneed** [expo/expo-docs#303]
https://docs.expo.io/versions/v27.0.0/sdk/haptic

"Private" is misspelled.

Current Text: 

"Using priavte API will get your app rejected"

Should Read: 
"Using private API will get your app rejected"

**Comment by brentvatne** [comment]
thanks, fixed in https://github.com/expo/expo-docs/commit/301099aa67b73bca973857cced19bf03e21b7a22

will be deployed next time docs go out
