### ISSUE TITLE
Playstore Your app currently targets API level 25 and must target at least API level 26 to ensure it is built on the latest APIs optimised for security and performance.

### ISSUE THREAD

**Issue by VishalVema** [expo/expo-docs#310]
When i am trying to roll out my app to the playstore it shows me an error message the snap of the error message is below please help me i have to rollout my app your help is appreciated 
![issue target api](https://user-images.githubusercontent.com/22855727/41039165-321bf742-69b6-11e8-94b9-9f401ee90648.PNG)

**Comment by AdamJNavarro** [comment]
Hey @VishalVema,

This is just a warning and it does not inhibit you from rolling your app out. I'd double check everything else in the Play Console to see what is actually making you unable to rollout. We are making the change so our builders target API Level 26 very soon. https://blog.expo.io/breaking-change-coming-to-android-apps-3116927f0424

Cheers,

Adam

**Comment by VishalVema** [comment]
Thank you so much and yes you are right it was the problem of content rating and store listing my bad and now everything working fine
