### ISSUE TITLE
Mention the new no publish flag in the docs

### ISSUE THREAD

**Issue by gregbenner** [expo/expo-docs#318]
[This issue](https://github.com/expo/expo/issues/63#issuecomment-399213261) was recently [resolved](https://github.com/expo/exp/blob/master/CHANGELOG.md#added-8) and it was mentioned there is a `--no-publish` flag 🎉
but it's nowhere in the [docs](https://docs.expo.io/versions/latest/distribution/building-standalone-apps#__next) so probably most people won't be able to find it

It's a great way to test some features that only work in production without rolling out to every client.

(I don't think release channels is explicit as an alternative solve, and when they first came out I encountered an issue if the SDK version changed it would roll out to all clients and it was difficult to rollback.)

**Comment by jimmylee** [comment]
Thanks for bringing this up @gregbenner, we'll incorporate this into our documentation.

**Comment by gregbenner** [comment]
No worries I would be happy to help with documentation if you need (in the future), but I would need some tips as to how you like to word things.
