### ISSUE TITLE
I'm trying to use audio in expo from this link https://docs.expo.io/versions/latest/sdk/audio.html and it works fine until I replace the string inside require function with dynamic variable string!! It gives me error that "require() must have a single string literal argument" and I can't fix it

### ISSUE THREAD

**Issue by Nermin-K** [expo/expo-docs#323]

**Comment by Nermin-K** [comment]
yeah, I got this at the end but it still very annoying that there is no alternative thing to help me reach my wish.

**Comment by davidmargolin** [comment]
agreed

**Comment by eriveltonelias** [comment]
Hi @Nermin-K 

Looks like it isn't a problem related with **Expo** because on react-native you need to call it statically. Maybe to resolve your problem, try to save your "music" on the server and call it dynamic using 
`{ uri: 'http://path/to/file' }`

**Comment by jimmylee** [comment]
Hey folks,

I'm going to have to ask you guys to move this question to the forums (https://forums.expo.io). More people will see your question and be able to lend a hand.

@eriveltonelias thank you for jumping in. Sorry about the issues if it is a problem on our end. We'll work hard to get things right.
