### ISSUE TITLE
Get base64 encoding for recorded audio and video

### ISSUE THREAD

**Issue by AakashRainaClairvoyant** [expo/expo-docs#325]
Hello, 

I want to get the base64 encoding for the audio/video I recorded, however, I'm not able to do so using expo. I have to store the audio/video on S3(we are using aws mobile hub for backend along with aws amplify). We also tried storing the blob on S3 but it doesn't seem to work. I have been able to store the audio/video file on the device using the media library API. Is there any way I could get the base64 encoding for the audio/video file?
NOTE: I have also tried using react-native-fetch-blob but it uses linking which is not supported by the expo.

**Comment by jimmylee** [comment]
Hey @AakashRainaClairvoyant! I recommend posting this to https://forums.expo.io since this repository is for feedback about the documentation.
