### ISSUE TITLE
Help with Notifications -- sorry formating is trash

### ISSUE THREAD

**Issue by RishabBhandari** [expo/expo-docs#336]
I want my code to have a notification toggle, where the notifications would stop if the user turns off the  switch, and turn on if the switch is on. However, such is not the case and the notifications keep coming in regardless of if the switch is on or off. Help would be greatly appreciated as I have spent countless hours on this one functionality. Thanks 

___ 
`
export default class Timer extends React.Component {
  render() {
      return (
          <View style={{paddingLeft: 15, flex: 1, flexDirection: 'column', justifyContent: 'center'}}>
              <View style={{height: 100, width: 100, flexDirection: 'row'}}></View>
              <Text> Enter Notificaiton Timer </Text>
              <View>
              {this.renderElement()}
              </View>
              <Switch style = {{height: 300}}
                onValueChange={this._handleToggleSwitch}
                value={this.state.switchValue}
              />
          </View>
      );
  }
  state = {
    switchValue: false,
  };
  _handleToggleSwitch = () =>
    this.setState(state => ({
      switchValue: !state.switchValue,
    }));
    onSubmit(e) {
        Keyboard.dismiss();
        const localNotification = {
            title: 'restart 3.0',
            body: 'done!',
            sound: 'true'
        };
        const schedulingOptions = {
            time: (new Date()).getTime() + Number(e.nativeEvent.text)+1000,
            repeat: 'minute'
        }
        // Notifications show only when app is not active.
        // (ie. another app being used or device's screen is locked)
        Notifications.scheduleLocalNotificationAsync(
              localNotification, schedulingOptions
        );
      }

    handleNotification() {
        console.warn('Notification Working');
      }
    async componentDidMount() {
        // We need to ask for Notification permissions for ios devices
        let result = await Permissions.askAsync(Permissions.NOTIFICATIONS);
        if(this.state.switchValue){
        if (Constants.isDevice && result.status === 'granted') {
            console.log('Notification permissions granted.')
        }
      }
        // If we want to do something with the notification when the app
        // is active, we need to listen to notification events and
        // handle them in a callback
      if (this.state.switchValue){
        Notifications.addListener(this.handleNotification);
        }
      }
        // Notifications.remove(); <- How do I implement this?
    renderElement(){
       if(this.state.switchValue){
          return   <TextInput onSubmitEditing={this.onSubmit} placeholder={'time in ms'}/>;
          Notifications.addListener(remove());
    }
  }
}'

**Comment by eriveltonelias** [comment]
Hi @RishabBhandari !

Why don't you try to it on your server? Basically, when the user turns off the notification you can save it on your database and before send notification check if the user wants to receive the notification ( checking it on your database ).

For Q&A try to use [StackOverflow](https://stackoverflow.com/), the community can help you faster than create a issue on Expo.

**Comment by RishabBhandari** [comment]
Can you provide an example? Im a little confused by what you mean to keep it on a server. 

Thanks

**Comment by jimmylee** [comment]
@eriveltonelias thank you so much for jumping in here. @RishabBhandari I'm going to close this thread, please ask this question on the forums https://forums.expo.io -- that way more people can help you and more people will see your question.

Cheers!
