### ISSUE TITLE
Expo fingerprint user_cancel Android

### ISSUE THREAD

**Issue by xperiafan13-rom** [expo/expo-docs#339]
Random times i get:
14:03:05: Object {
14:03:05:   "error": "user_cancel",
14:03:05:   "message": "Se canceló la operación de huella digital.",
14:03:05:   "success": false,
14:03:05: }

Im restart the app and same message, other times, all is working god.
Im test this only on Android

  "dependencies": {
    "@expo/vector-icons": "^6.3.1",
    "expo": "^28.0.0",
    "install": "^0.12.1",
    "native-base": "^2.7.2",
    "react": "16.3.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz",
    "react-native-simple-dialogs": "^0.3.1",
    "react-navigation": "^2.9.2",
    "rn-prompt": "^1.0.3"
  },

**Comment by jimmylee** [comment]
Hey @xperiafan13-rom I recommend posting this on the forums https://forums.expo.io since this repository is for changes to our documentation.
