### ISSUE TITLE
Installation instructions for latest simulator build not working

### ISSUE THREAD

**Issue by peterkuiper** [expo/expo-docs#347]
From: https://docs.expo.io/versions/latest/introduction/installation#ios-simulator

Unpacking does not generate a `Exponent-x.y.z.app` directory. When using `tar`, files are extracted in the current directory.

Trying to copy the directory without the .app extension generates the following error:

```
xcrun simctl install booted Exponent-x.y.z
An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
This app could not be installed at this time.
Underlying error (domain=MIInstallerErrorDomain, code=6):
	No installable items found at /path/to/data/Library/Caches/com.apple.mobile.installd.staging/temp.vvBoF0/extracted/Payload
```
This does work:

```
mkdir Exponent-x.y.z.app && tar xvf Exponent-x.y.z.tar.gz -C Exponent-x.y.z.app
xcrun simctl install booted Exponent-x.y.z.app
```

**Comment by jimmylee** [comment]
Thanks for pointing this out, I'm not an expert on this topic but if you want to submit a PR that would be super helpful :-)

**Comment by peterkuiper** [comment]
@jimmylee https://github.com/expo/expo-docs/pull/361 HTH
