### ISSUE TITLE
Amplitude Documentation Example

### ISSUE THREAD

**Issue by tushgup** [expo/expo-docs#354]
Hey guys, I'm not able to find any examples for setting up Amplitude Analytics on Expo.

The example link in the docs is broken. 

Link: https://docs.expo.io/versions/latest/sdk/amplitude.html
Example Broken Link: https://github.com/expo/expo/blob/master/js/api/Analytics.js

**Comment by jimmylee** [comment]
@tushgup thank you so much for bringing this up!

I'm not an expert so if anyone is able to send a pull request that would be super useful.

**Comment by johntips** [comment]
I can't find any docs those links too.
If you found any correct links , please PR!!
