### ISSUE TITLE
XDE Client missing on browser

### ISSUE THREAD

**Issue by FrederickEngelhardt** [expo/expo-docs#358]
Not sure if this is an issue but I was looking for the XDE client and could not find it. There is still documentation on how to use it but I cannot find a link on the main page to download the client on Mac or Windows. (I'm on a Mac while viewing the web on chrome browser).

**Comment by davidmargolin** [comment]
yeah it sucks that they removed it from the main page. Downloads are here: https://github.com/expo/xde/releases
