### ISSUE TITLE
sh : npm install react-navigation --save problem.

### ISSUE THREAD

**Issue by vzsky** [expo/expo-docs#383]
as in the working environment directory, I ran 
``` npm install react-navigation --save ```
and I tracked the installation manually.
I found out that the installation cause some problem 

this is the node_modules directory **before** the installation 
<img width="583" alt="screen shot 2561-10-16 at 10 48 30" src="https://user-images.githubusercontent.com/20735983/46991661-09093080-d131-11e8-84ef-e06cf07293d3.png">

and this is the node_modules directory **after** the installation
<img width="585" alt="screen shot 2561-10-16 at 10 49 42" src="https://user-images.githubusercontent.com/20735983/46991701-33f38480-d131-11e8-9437-95b299118f81.png">

as you can see that the files in that directory disappeared! It then cause a huge problem to the react-native app.

To solve that for the users, I suggest copying all sub-directory in the node_modules before the installation. then after the installation, just replace it in the installed node_modules directory.

**Comment by brentvatne** [comment]
this is a bug with npm. you can delete your node_modules and package-lock.json and then run `npm install` to fix it. i suggest using yarn instead though
