### ISSUE TITLE
Expo.Audio.Sound.createAsync doesn't exist?

### ISSUE THREAD

**Issue by brettdh** [expo/expo-docs#407]
The [Audio docs](https://docs.expo.io/versions/latest/sdk/audio.html) refer to `Audio.Sound.createAsync`, but in my Expo SDK (30.0.0), there's only `Audio.Sound.create`.

Just getting started with the Audio API; I will update this with any other staleness I find.

**Comment by brettdh** [comment]
Gah, of course I was viewing "latest` instead of "v30.0.0".

Was there a deprecation notice here? Is it commonplace to rename methods without leaving a backwards compatibility version? This makes it pretty hard to use the Expo docs if I'm not always upgrading on release day.

**Comment by brettdh** [comment]
Not mentioned in the [31.0.0 changelog](https://github.com/expo/expo/blob/master/CHANGELOG.md#3100-partial-changelog), for instance; only in the [release announcement](https://blog.expo.io/expo-sdk-v31-0-0-is-now-available-cad6d0463f49), which seems like it would be _less_ authoritative and comprehensive. Very confused.

**Comment by brentvatne** [comment]
cc @esamelson

**Comment by esamelson** [comment]
Hi @brettdh - thanks for letting us know about this discrepancy. I've updated the changelog to reflect this correctly. We only started using a changelog midway through this cycle, so unfortunately a few changes that happened early on got missed (note that it says `Partial Changelog` for 31.0.0). We'll do better about documenting everything there in the future.

**Comment by brettdh** [comment]
@esamelson Thanks. I wonder if there's also a way to be more explicit about when APIs were introduced? For instance, I notice that `Sound.create` actually does still exist in SDK 31; it's just not mentioned in the docs. It might also be useful to have a note about when an API was introduced or changed, as (for example) the Python and Node.js docs do - as well as deprecation information inline with the docs.

**Comment by esamelson** [comment]
@brettdh - thanks for this feedback. We're looking at doing a significant overhaul to our docs in the near future and we'll take this into consideration.
