### ISSUE TITLE
Should exp.json be renamed app.json?

### ISSUE THREAD

**Issue by 8ctopotamus** [expo/expo-docs#49]
I see references to exp.json all over the documentation, but when using `create-react-native-app appName`, an app.json file is generated. I assume this should be used the same way as exp.json from the docs?

**Comment by sonaye** [comment]
Yes it's the same but more general. With regards to renaming, I think it would make sense now to rename `exp.json` to `expo.json` and `exp` cli to `expo` as well.

cc: @jesseruder

**Comment by brentvatne** [comment]
@8ctopotamus - indeed exp.json is the expo specific version of app.json. @sonaye those are valid points, we're actively working to make this as clear as possible so we'll consider this option!
