### ISSUE TITLE
How to change status bar notification icon?

### ISSUE THREAD

**Issue by 8ctopotamus** [expo/expo-docs#51]
How do you define a notification icon for the status bar? I created a 48x48px png and set that in app.json under "Notification". 

It worked for the actual notification message, but still used the little exponent icon in the status bar. How do I change the status bar notification Icon?

**Comment by sonaye** [comment]
Standalone builds only.

**Comment by 8ctopotamus** [comment]
Cool, is this also the case when you "eject" an expo app into a regular RN app? What is the difference between using "eject" and a standalone build?

**Comment by 8ctopotamus** [comment]
Also, will Expo push notifications work in a standalone app?

**Comment by brentvatne** [comment]
yes @8ctopotamus, but not if you "eject"

**Comment by brentvatne** [comment]
feel free to take further questions to http://forums.expo.io/ :)

**Comment by 8ctopotamus** [comment]
> yes @8ctopotamus, but not if you "eject"

What is the difference between a "standalone" app and an "ejected" app?

**Comment by brentvatne** [comment]
Standalone app: https://docs.expo.io/versions/v16.0.0/guides/building-standalone-apps.html
Detached app (commonly called "ejected"): https://docs.expo.io/versions/v16.0.0/guides/detach.html

**Comment by 8ctopotamus** [comment]
Got it, thank you ver much!
