### ISSUE TITLE
Clarification Needed: Preloading & Caching Assets

### ISSUE THREAD

**Issue by gsklee** [expo/expo-docs#74]
https://docs.expo.io/versions/v17.0.0/guides/preloading-and-caching-assets.html

Do the steps detailed in this article need to be implemented by developers? I thought it's said somewhere (https://docs.expo.io/versions/v17.0.0/guides/assets.html) that assets are managed automatically by Expo in both develop and production modes?

**Comment by brentvatne** [comment]
Preloading and caching assets is useful for assets that need to be displayed immediately. For example, fonts, icons, your logo. Expo handles uploading all of your assets to a CDN but it does not include them all inside of your app binary, it fetches them on-demand unless you tell your app to download and cache. In development, the asset resolves to a url on your development server, and in production it resolves to a url on CloudFront, and once it's cached it resolves to a local filesystem url.
