### ISSUE TITLE
What license are the docs distributed under?

### ISSUE THREAD

**Issue by morenoh149** [expo/expo-docs#80]
I'd like to submit expo docs to devdocs.io as that is my primary way of consuming documentation.

What license are the expo docs distributed under?

See also https://trello.com/c/PVnfdeaN/26-suggest-new-docs-here

**Comment by brentvatne** [comment]
hello! expo software and docs are distributed under bsd license, see: https://github.com/expo/expo/blob/master/LICENSE

let me know if we can help with devdocs.io integration!

**Comment by morenoh149** [comment]
submitted https://trello.com/c/PVnfdeaN/26-suggest-new-docs-here#comment-5947e0178c017a7b953b3159
