### ISSUE TITLE
Expo XDE Tour Screenshot out of date?

### ISSUE THREAD

**Issue by jkeesh** [expo/expo-docs#83]
I think the top screenshot on this page: https://docs.expo.io/versions/v18.0.0/introduction/xde-tour.html

https://docs.expo.io/39020a972467e2c712b463f40ed9759d-quality=50&pngCompressionLevel=9&width=1064.png

Is out of date. I just downloaded the app on a mac and the register screen did not look like that.

**Comment by brentvatne** [comment]
hard to keep screenshots up to date when we iterate on the UI a bunch, but we should do a better job at it. I'll try to do this next week

**Comment by jkeesh** [comment]
yeah it is a lot to update but does help for new people to keep the docs up
to date
ᐧ

**Comment by brentvatne** [comment]
done! will be deployed soon
