### ISSUE TITLE
More details on packagerOpts

### ISSUE THREAD

**Issue by pensierinmusica** [expo/expo-docs#90]
Hi,

Can you please provide more details on what `packagerOpts` does?

https://docs.expo.io/versions/v18.0.0/guides/configuration.html#packageropts

https://github.com/expo/expo-docs/blob/master/versions/v18.0.0/guides/configuration.md

Thanks!

**Comment by brentvatne** [comment]
Good point, we should add more information on this. Basically it allows you to pass in options to the React Native packager, the problem is the React Native packager doesn't really document its options either.. generally you shouldn't need this. Is there something specific that you're trying to do?

**Comment by brentvatne** [comment]
I created this issue to request documentation for packager options: https://github.com/facebook/metro-bundler/issues/26

**Comment by HuiSF** [comment]
Hi, in (How Expo Works)[https://github.com/expo/expo-docs/blob/master/versions/v20.0.0/guides/how-expo-works.md], there is a example of `app.json`. It includes `packagerOpts` like blow:

```json
"packagerOpts":{
  "hostType":"tunnel",
  "dev":false,
  "strict":false,
  "minify":false,
  "urlType":"exp",
  "urlRandomness":"2v-w3z",
  "lanType":"ip"
}
```
I tried `dev` and `minify`, these two options. When I start the packager, it throws:

```
error: unknown option `--minify'
error: unknown option `--dev'
```

This documentation seems outdated and inaccurate. Could you please update? Thanks.

**Comment by brentvatne** [comment]
hi @HuiSF - I believe you read the docs incorrectly, what you see there is not an example of an app.json but of an app manifest

**Comment by HuiSF** [comment]
Thanks @brentvatne

**Comment by martsie** [comment]
Sorry to re-open this issue but what is the app manifest? I've been looking at https://github.com/expo/expo-docs/blob/master/versions/v23.0.0/guides/how-expo-works.md but the only file it mentions is app.json. I'd like to change the dev flag and minify flag so that I can debug a production build of my app.

**Comment by kotakpensil** [comment]
cmiiw

```
let packagerOpts = {
      port: packagerPort,
      customLogReporterPath: _path.default.join(nodeModulesPath, 'expo', 'tools', 'LogReporter'),
      assetExts: ['ttf'],
      nonPersistent: !!options.nonPersistent
};
```
