### ISSUE TITLE
entryPoint doesn't seem to work

### ISSUE THREAD

**Issue by pensierinmusica** [expo/expo-docs#91]
Hi,

The docs list an option named `entryPoint` to indicate the entry point of the app:

https://docs.expo.io/versions/v18.0.0/guides/configuration.html#entrypoint

It doesn't seem to work though, as the entry point is actually hardcoded into [`node_modules/expo/AppEntry.js`](https://github.com/expo/expo-sdk/blob/master/AppEntry.js#L2).

Am I missing something?

Thanks!

**Comment by brentvatne** [comment]
I pinged @ide, I think he added this and I'm not sure what it is for. We use the `main` from package.json -- you can change it there if you want, just keep in mind that you will need to use [Expo.registerRootComponent](https://docs.expo.io/versions/v18.0.0/sdk/register-root-component.html) if you do, rather than just `export default`.

**Comment by brentvatne** [comment]
indeed this should be removed from docs and from app.json

**Comment by pensierinmusica** [comment]
👍🏾

**Comment by brentvatne** [comment]
created issue for this internally, we will remove entry point entirely

**Comment by isaachinman** [comment]
@brentvatne So is it not possible to specify a custom entry point? Seems like a valid (and easy) thing to support. Regardless, `entryPoint` is still in the docs.

**Comment by rigorojas** [comment]
in package.js
----
{
  "main": "./index.expo.js",
  ...
}

in index.expo.js
----
import { KeepAwake, registerRootComponent } from 'expo';
import App from './src/Main.js';

if (__DEV__) {
  KeepAwake.activate();
}

registerRootComponent(App);


----
Works as expected for me.

**Comment by brentvatne** [comment]
`main` works, it's the `entryPoint` key that doesn't :)

**Comment by isaachinman** [comment]
Yes sorry, I found this info elsewhere and forgot to report back here. The desired effect is possible via `main` and `registerRootComponent`, but `entryPoint` is indeed misleading and broken.

**Comment by moshfeu** [comment]
@rigorojas seems to be `__DEV__` rather than `DEV`, right?
