### ISSUE TITLE
There's no clear description on how to preload and cache images

### ISSUE THREAD

**Issue by pensierinmusica** [expo/expo-docs#92]
Hi,

The docs describe how to preload and cache images here:

https://docs.expo.io/versions/v18.0.0/guides/preloading-and-caching-assets.html

It is not clear though whether we should use [`Expo.AppLoading`](https://docs.expo.io/versions/v18.0.0/sdk/app-loading.html#app-loading) as described at the top, or the technique described at the bottom in [`github/exponent/new-project-template`](https://github.com/expo/new-project-template/blob/9c5f99efa9afcbefdadefe752ea350cc378c0f0d/main.js).

Can you please clarify what is the suggested approach? Thanks!

**Comment by brentvatne** [comment]
Hi @pensierinmusica! It's not clear to me what the difference is -- both of these use the AppLoading component. Can you elaborate? This is definitely an area of the docs that we need to improve. Any more info you can give around what specifically is confusing will be very helpful.

**Comment by brentvatne** [comment]
Hopefully this is a little more clear than before: https://github.com/expo/new-project-template/blob/8ce3ef71bbc7645225870f9c7c40ea7fe34b8cf9/App.js#L32-L39

I'll update docs accordingly

**Comment by abi** [comment]
Closing, because I think it's clear enough in the docs now.
