### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by kiok46** [expo/expo-docs#93]
Link to expo-auth0-example repository is broken and leads to 404. https://docs.expo.io/versions/v18.0.0/guides/using-graphql.html#social-oauth-authentication-providers

In the docs: https://github.com/expo/expo-docs/blob/master/versions/v18.0.0/guides/using-graphql.md#social-oauth-authentication-providers

**Comment by brentvatne** [comment]
fixed, thanks!
