### ISSUE TITLE
docsearch not working in Safari 

### ISSUE THREAD

**Issue by Haroenv** [expo/expo-docs#94]
I have a feeling it’s an unrelated part of the javascript that’s not executing, and thus also not executing the search: 

<img width="338" alt="screen shot 2017-07-08 at 16 55 15" src="https://user-images.githubusercontent.com/6270048/27986345-5fb91b9e-63fe-11e7-8df7-6c08f565a600.png">
<img width="542" alt="screen shot 2017-07-08 at 16 54 57" src="https://user-images.githubusercontent.com/6270048/27986346-5fdd462c-63fe-11e7-93be-2a9801285266.png">

**Comment by brentvatne** [comment]
fixed, thanks

**Comment by Haroenv** [comment]
Top, it works :100:
